# Generated by Django 5.1.1 on 2024-09-10 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_page',
            field=models.CharField(default='title_page', max_length=255),
        ),
    ]
